BootstrapHtml:
    external_svc_url: !spec
        description: external svc url
        type: !uri ""
        value: !uri http://bshtml.fyre/api/v1.0/bootstrap/fyre.conv/
    web_port: !spec
        description: web port
        type: !!int "0"
        value: !required "cluster.yaml"
    redis_host: !spec
        description: redis host location
        type: !!str ""
        value: !required "cluster.yaml"
    redis_port: !spec
        description:
        type: !!int "0"
        value: 6379
    statsd_host: !spec
        description: StatsD server config
        type: !uri ""
        value: !uri "statsd://statsd-ops-1:8125"

environment:
    type: !spec
        description: Environment where the app is being run
        type: !!str ""
        value: !required "cluster.yaml"
