#!/bin/bash
echo "Starting..."

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SWD="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
cd $SWD
if [ "`uname`" = "Darwin" ]; then
        node $SWD/node_modules/yamljs/yamljs.js $SWD/src/config/app.yaml $SWD/src/config/env_darwin.yaml /etc/livefyre/cluster.yaml > $SWD/config.json
        NEWRELIC__APP_NAME=$USER-irt
else
         node $SWD/node_modules/yamljs/yamljs.js $SWD/src/config/app.yaml /etc/livefyre/cluster.yaml > $SWD/config.json
fi
chmod 755 $SWD/config.json
exec node ${SWD}/src/runconsumer.js
